kind: pipeline
name: publish

steps:

- name: build
  image: anoff/hugo-asciidoctor
  commands:
  - hugo --gc --minify -d _site --baseURL //devradar.io
  - touch _site/.nojekyll

- name: netlify deploy
  image: node:lts-alpine
  environment:
    NETLIFY_SITE_ID:
      from_secret: NETLIFY_ID
    NETLIFY_AUTH_TOKEN:
      from_secret: NETLIFY_TOKEN
  commands:
    - npm install -g netlify-cli
    - netlify deploy --dir=_site --prod
  # when:
  #   branch:
  #   - master
