baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "devradar.io | your personal techradar"
theme = "kross-techradar"
summaryLength = "10"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"
  
# navigation
[params.nav]
  [[params.nav.link]]
  URL = "//editor.devradar.io"
  Name = "Editor"
  [[params.nav.link]]
  URL = "//docs.devradar.io"
  Name = "Docs"

[params]
logo = "images/devradar-b.png"
home = "Home"
# Meta data
description = "Your personal techradar"
author = "Andreas Offenhaeuser"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # github (fork) corner
  [params.github]
  enable = true
  URL = "//github.com/anoff/devradar"

  # Preloader
  [params.preloader]
  enable = true

  [params.footer]
  email = "steve.fruits@email.com"
  phone = "+880 2544 658 256"
  address = "125/A, CA Commercial Area, California, USA"